version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - "npm install"
  build:
    commands:
      - "echo 'Build started on' $(date)"

artifacts:
  files:
    - "index.js"
    - "package.json"
    - "package-lock.json"
    - "node_modules/**/*"
    - ".gitignore"
    - "buildspec.yml"
  discard-paths: no
